### ISSUE TITLE
能不能分享一下数据库文件

### ISSUE THREAD

**Issue by iniwym** [GithubWangXiaoXi/mheal#3]
感谢开源，能不能分享一下数据库文件。

**Comment by GithubWangXiaoXi** [comment]
抱歉，之前我忘记把sql文件保存起来了，我刚刚创建了一个新的sql文件，你看看能不能用（里面没有数据，只有字段）
sql文件内容如下（我这里用的是5.7的mysql，如果用低版本的mysql导入可能会有问题）：

/*
Navicat MySQL Data Transfer

Source Server         : mysql1
Source Server Version : 50731
Source Host           : localhost:3306
Source Database       : mheal

Target Server Type    : MYSQL
Target Server Version : 50731
File Encoding         : 65001

Date: 2021-05-25 10:54:26
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for activity
-- ----------------------------
DROP TABLE IF EXISTS `activity`;
CREATE TABLE `activity` (
  `id` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `startTime` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `endTime` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `place` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `requirement` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of activity
-- ----------------------------

-- ----------------------------
-- Table structure for admin
-- ----------------------------
DROP TABLE IF EXISTS `admin`;
CREATE TABLE `admin` (
  `id` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `username` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `gender` tinyint(2) DEFAULT NULL,
  `age` smallint(10) DEFAULT NULL,
  `department` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `tel` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of admin
-- ----------------------------

-- ----------------------------
-- Table structure for askandans
-- ----------------------------
DROP TABLE IF EXISTS `askandans`;
CREATE TABLE `askandans` (
  `id` int(255) NOT NULL,
  `q_id` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `s_id` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `d_id` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `answer` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `updateTime` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of askandans
-- ----------------------------

-- ----------------------------
-- Table structure for chat_friends
-- ----------------------------
DROP TABLE IF EXISTS `chat_friends`;
CREATE TABLE `chat_friends` (
  `id` int(11) NOT NULL,
  `userid` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL,
  `fuserid` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL,
  `addtime` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of chat_friends
-- ----------------------------

-- ----------------------------
-- Table structure for doctor
-- ----------------------------
DROP TABLE IF EXISTS `doctor`;
CREATE TABLE `doctor` (
  `id` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `username` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `gender` tinyint(2) DEFAULT NULL,
  `age` smallint(10) DEFAULT NULL,
  `teachYear` smallint(10) DEFAULT NULL,
  `graduatedSchool` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `tel` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of doctor
-- ----------------------------

-- ----------------------------
-- Table structure for document
-- ----------------------------
DROP TABLE IF EXISTS `document`;
CREATE TABLE `document` (
  `id` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `author` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `href` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `content` blob,
  `createTime` datetime DEFAULT NULL,
  `updateTime` datetime DEFAULT NULL,
  `viewCount` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `likes` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of document
-- ----------------------------

-- ----------------------------
-- Table structure for joinactivities
-- ----------------------------
DROP TABLE IF EXISTS `joinactivities`;
CREATE TABLE `joinactivities` (
  `id` int(255) NOT NULL AUTO_INCREMENT,
  `a_id` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `s_id` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `ad_id` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of joinactivities
-- ----------------------------

-- ----------------------------
-- Table structure for login
-- ----------------------------
DROP TABLE IF EXISTS `login`;
CREATE TABLE `login` (
  `id` int(11) NOT NULL,
  `userid` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL,
  `username` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of login
-- ----------------------------

-- ----------------------------
-- Table structure for music
-- ----------------------------
DROP TABLE IF EXISTS `music`;
CREATE TABLE `music` (
  `id` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `author` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `href` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `bgm` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `createTime` datetime DEFAULT NULL,
  `updateTime` datetime DEFAULT NULL,
  `viewCount` int(11) DEFAULT NULL,
  `likes` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of music
-- ----------------------------

-- ----------------------------
-- Table structure for question
-- ----------------------------
DROP TABLE IF EXISTS `question`;
CREATE TABLE `question` (
  `id` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `createTime` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `updateTime` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `content` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `likes` int(255) DEFAULT NULL,
  `viewCount` int(255) DEFAULT NULL,
  `anonymous` tinyint(2) DEFAULT NULL,
  `status` tinyint(2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of question
-- ----------------------------

-- ----------------------------
-- Table structure for questionandtag
-- ----------------------------
DROP TABLE IF EXISTS `questionandtag`;
CREATE TABLE `questionandtag` (
  `id` int(255) NOT NULL AUTO_INCREMENT,
  `q_id` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `t_id` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of questionandtag
-- ----------------------------

-- ----------------------------
-- Table structure for resourceandtag
-- ----------------------------
DROP TABLE IF EXISTS `resourceandtag`;
CREATE TABLE `resourceandtag` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `r_id` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `t_id` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of resourceandtag
-- ----------------------------

-- ----------------------------
-- Table structure for student
-- ----------------------------
DROP TABLE IF EXISTS `student`;
CREATE TABLE `student` (
  `id` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `username` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `gender` tinyint(2) DEFAULT NULL,
  `age` smallint(10) DEFAULT NULL,
  `tel` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of student
-- ----------------------------

-- ----------------------------
-- Table structure for tag
-- ----------------------------
DROP TABLE IF EXISTS `tag`;
CREATE TABLE `tag` (
  `id` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `tagName` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of tag
-- ----------------------------

-- ----------------------------
-- Table structure for userinfo
-- ----------------------------
DROP TABLE IF EXISTS `userinfo`;
CREATE TABLE `userinfo` (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `userid` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL,
  `nickname` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL,
  `usign` varchar(512) COLLATE utf8mb4_bin DEFAULT NULL,
  `uimg` varchar(512) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of userinfo
-- ----------------------------

-- ----------------------------
-- Table structure for video
-- ----------------------------
DROP TABLE IF EXISTS `video`;
CREATE TABLE `video` (
  `id` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `author` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `title` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `href` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `createTime` datetime DEFAULT NULL,
  `updateTime` datetime DEFAULT NULL,
  `viewCount` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `likes` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ----------------------------
-- Records of video
-- ----------------------------

**Comment by iniwym** [comment]
感谢，启动成功。
